bybit:
  apiKey:
  apiSecret:
  tradingNet: main

websocket:
  url:
  topic:

trade:
  downRecoverPercent: 70
  takeProfitPercent: 15
  stopLossPercent: 15
  buyAmountUsdt: 100.00

logging:
  level:
    root: INFO